repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: detect-private-key
      stages: [commit]
  - repo: https://github.com/crate-ci/committed
    rev: v1.0.20
    hooks:
    - id: committed
      stages: [commit-msg]
  - repo: https://github.com/crate-ci/typos
    rev: v1.20.9
    hooks:
      - id: typos