name: Test GitHub Action
on:
  push:
  pull_request:

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Use custom config file
      uses: crate-ci/typos@master
